# -*- coding: utf-8 -*-
"""TP4_Simulacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDwcozADiXcMSieL99h7P6IL00-bIyEe

# Trabajo práctico número 4
## Grupo 2

#Carga de bibliotecas
"""

pip install fitter

from fitter import Fitter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from google.colab import drive
drive.mount('/content/drive')

"""#Carga de datos"""

datos = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/TP4-SImulacion/Datos/hospital_data_sampleee.xlsx')

"""#Analisis"""

type(datos)

"""###CONTENIDO:
#####Date : Dia de la visita
#####Medication Revenue : Ganancia de la medicacion
#####Lab Cost : Costos de laboratorio pagado por el paciente
#####Consultation Revenue : Ganancia de la consulta
#####Doctor Type : Especialidad del doctor
#####Financial Class : Tipo de cobertura medica. [INSURANCE, PRIVATE, CORPORATE, HMO, MEDICARE]
#####Patient Type : OUTPATIENT, paciente sin internacion. Todos los registros
#####Entry Time : Hora de entrada al hospital
#####Post-Consultation Time : Hora de entrada a la consulta
#####Completion Time : Hora de salida del paciente
#####Patient ID : ID
"""

datos.head()

datos.shape

datos.dtypes

datos["Doctor Type"].value_counts()

"""####Tipo de medico:
#####Buscando el significado de ANCHOR, LOCUM, FLOATING entendemos que estos son medicos Titulares, Sustituto, Voluntario.
"""

datos["Date"].value_counts()

"""####Fechas
#####Las fechas corresponden a los primeros 13 dias de noviembre. Por lo tanto no tendremos discriminacion en cuanto a la fecha para crear diferentes variables aleatorias.
#####Aunque cabe remarcar que a excepcion del 13/11 los cuatro dias con menos pacientes atendidos corresponden a los dias sabado y domingo. Mientras que los dos dias con mas pacientes corresponden a un dia lunes.

#Preparación de datos

####Empezamos juntando la fecha a cada horario dejandolos en datetime.
"""

datos['Entry_Time_datetime'] = datos["Date"] + pd.to_timedelta(datos["Entry Time"].astype(str))

datos['Post_Consultation_Time_datetime'] = datos["Date"] + pd.to_timedelta(datos["Post-Consultation Time"].astype(str))

datos['Completion_Time_datetime'] = datos["Date"] + pd.to_timedelta(datos["Completion Time"].astype(str))

"""#####Chequeamos valores obtenidos."""

datos.head()

datos['Tiempo_consulta'] = datos['Completion_Time_datetime']-datos['Post_Consultation_Time_datetime']

datos.dtypes

"""#####Creamos valores de tiempo de consulta en segundos y minutos."""

datos['Tiempo_consulta_seg']=datos.Tiempo_consulta.dt.total_seconds()

datos['Tiempo_consulta_min']=datos.Tiempo_consulta_seg / 60

"""#####Filtramos consultas en medicos titulares y sustitutos."""

datos_titulares = datos[datos['Doctor Type'] == "ANCHOR"]

datos_sustitutos = datos[datos['Doctor Type'] == "LOCUM"]

"""#####Chequeamos variables creadas"""

datos_titulares.head()

datos_titulares.shape

datos_sustitutos.head()

datos_sustitutos.shape

datos_titulares.hist('Tiempo_consulta_min',bins=200)

datos_titulares.boxplot('Tiempo_consulta_min')

datos_titulares = datos_titulares.sort_values('Tiempo_consulta_min')

datos_titulares.head(400)

"""#####En este caso vemos que la salida del hospital sucede antes de la entrada a la clinica, consideraremos estos casos como arrepentidos.

#####Procederemos a filtrar los datos.
"""

datos_titulares_filtrados = datos_titulares[datos_titulares['Tiempo_consulta_min'] > 0]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_titulares_filtrados.boxplot('Tiempo_consulta_min')

"""Procederemos a acotar los tiempos."""

datos_titulares_filtrados = datos_titulares_filtrados[datos_titulares['Tiempo_consulta_min'] < 300]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_titulares_filtrados.boxplot('Tiempo_consulta_min')

datos_titulares_filtrados = datos_titulares_filtrados[datos_titulares['Tiempo_consulta_min'] < 100]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_titulares_filtrados.boxplot('Tiempo_consulta_min')

datos_titulares_filtrados = datos_titulares_filtrados[datos_titulares['Tiempo_consulta_min'] < 40]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_titulares_filtrados.boxplot('Tiempo_consulta_min')

datos_titulares_filtrados = datos_titulares_filtrados[datos_titulares['Tiempo_consulta_min'] < 25]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_titulares_filtrados.boxplot('Tiempo_consulta_min')

"""#####Conderamos que el pico en Tiempo = 0 corresponde a un error en como se mide el tiempo de los medicos, por lo que lo eliminaremos. Ejemplo, no se registra cuando entra el paciente a consulta y se marca la entrada y salida al mismo tiempo"""

datos_titulares_filtrados = datos_titulares_filtrados[datos_titulares['Tiempo_consulta_min'] > 1]

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

"""#####Tomaremos estos tiempos para el calculo del Tiempo de atención.

####Procedemos a hacer lo mismo para los tiempos de atencion de medicos Sustitutos.
"""

datos_sustitutos.hist('Tiempo_consulta_min',bins=200)

datos_sustitutos_filtrados = datos_sustitutos[(datos_sustitutos['Tiempo_consulta_min'] > 1)&(datos_sustitutos['Tiempo_consulta_min'] < 25)]

datos_sustitutos_filtrados.hist('Tiempo_consulta_min',bins=200)

"""####Ahora obtendremos nuestros datos filtrados para los arribos."""

datos = datos.sort_values('Entry_Time_datetime')

datos['Intervalo_arribos']=datos['Entry_Time_datetime'].diff()

datos['Intervalo_arribos_min']=datos.Intervalo_arribos.dt.total_seconds() / 60

datos.head(400)

datos.hist('Intervalo_arribos_min',bins=200)

datos.boxplot('Intervalo_arribos_min')

"""#####Consederamos los valores altos la diferencia entre llegadas de dias diferentes. No seran tenidos en cuenta."""

datos_filtrados = datos[datos['Intervalo_arribos_min'] < 100]

datos_filtrados.hist('Intervalo_arribos_min',bins=200)

"""Procedemos a acotar los valores."""

datos_filtrados = datos_filtrados[datos_filtrados['Intervalo_arribos_min'] < 10]

datos_filtrados.hist('Intervalo_arribos_min',bins=200)

datos_filtrados = datos_filtrados[datos_filtrados['Intervalo_arribos_min'] < 2]

datos_filtrados.hist('Intervalo_arribos_min',bins=200)

"""###Histogramas finales.
#####En orden, tiempo de atencion de titulares, tiempo de atencion e suplentes, tiempo entre arribos
"""

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_sustitutos_filtrados.hist('Tiempo_consulta_min',bins=200)

datos_filtrados.hist('Intervalo_arribos_min',bins=200)

"""###Creamos fdp"""

fdp_TAT = Fitter(datos_titulares_filtrados.Tiempo_consulta_min)

fdp_TAT.fit()

fdp_TAT.summary(10)

fdp_TAS = Fitter(datos_sustitutos_filtrados.Tiempo_consulta_min)

fdp_TAS.fit()

fdp_TAS.summary(10)

fdp_IA = Fitter(datos_filtrados.Intervalo_arribos_min)

fdp_IA.fit()

fdp_IA.summary(10)

"""###Simulamos un set de datos para cada variable.

#####Intervalo entre arribos
"""

fdp_IA.get_best(method='sumsquare_error')

a_IA = np.float64(0.8506787350048977)
b_IA = np.float64(119.16563440533798)
loc_IA = np.float64(-5.039976276199166e-28)
scale_IA = np.float64(34.07584894426459)

fdp_IA_beta = stats.beta.rvs(a_IA, b_IA, loc=loc_IA, scale=scale_IA ,size=30000)

# Histograma de datos de verificación
plt.title("Histograma")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.xlim(0, 2)
plt.ylim(0, 3000)
plt.hist(fdp_IA_beta, bins=150)
plt.show()

datos_filtrados.hist('Intervalo_arribos_min',bins=200)

"""#####Tiempo de atencion titulares"""

fdp_TAT.get_best(method='sumsquare_error')

dfn_TAT = np.float64(1.8565442689118927)
dfd_TAT = np.float64(38.61216990606688)
loc_TAT = np.float64(1.016666666666666)
scale_TAT = np.float64(4.023906662604354)

fdp_TAT_f = stats.f.rvs(dfn_TAT, dfd_TAT, loc=loc_TAT, scale=scale_TAT, size=30000)

# Histograma de datos de verificación
plt.title("Histograma")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.xlim(0, 25)
plt.ylim(0, 3000)
plt.hist(fdp_TAT_f, bins=150)
plt.show()

datos_titulares_filtrados.hist('Tiempo_consulta_min',bins=200)

"""#####Tiempo de atencion Suplentes"""

fdp_TAS.get_best(method='sumsquare_error')

c_TAS = np.float64(0.118507044920764)
loc_TAS = np.float64(1.0166666660287709)
scale_TAS = np.float64(3.4662681374907205)

fdp_TAS_genpareto = stats.genpareto.rvs(c_TAS, loc=loc_TAS, scale=scale_TAS,size = 30000)

# Histograma de datos de verificación
plt.title("Histograma")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.xlim(0, 25)
plt.ylim(0, 4000)
plt.hist(fdp_TAS_genpareto, bins=150)
plt.show()

datos_sustitutos_filtrados.hist('Tiempo_consulta_min',bins=200)

"""####Por ultimo analizaremos si existe una diferencia significativa entre el tiempo de atencion de titulares y suplentes. Asi definiremos si tiene sentido usar dos variables aleatorias.

#####Usaremos el test de Kolmogorov-Smirnov. Si el resultado de este es 0 son la misma distribucion, si es 1 son completamente diferentes.
"""

ks_stat, p_value = stats.ks_2samp(fdp_TAS_genpareto, fdp_TAT_f)

print("KS statistic:", ks_stat)
print("p-value:", p_value)

"""#####Como vemos los valores obtenidos son muy cercanos a cero. Por lo que definiremos a fdp_TAT como representativa de todo el tiempo de atencion. Elegimos esta por tener la muestra mas grande.

###Conclusión.

A lo largo de este trabajo se procesó y analizó el conjunto de datos correspondientes a la atención de los pacientes en un hospital. Inicialmente se descubrió inconsistencias en algunos datos, como tiempos negativos o valores no comunes, los cuales fueron filtrados para obtener muestras representativas.

 Posteriormente, se construyeron variables relevantes para la simulación, como el tiempo de atención y los intervalos entre arribos de los pacientes. A partir de estas variables se analizaron sus distribuciones mediante histogramas.

 Se aplicaron técnicas de ajuste de funciones de densidad de probabilidad (FDP) utilizando la libreria Fitter, obteniendo como mejores aproximaciones una distribución Beta para los intervalos entre arribos, una distribución F para los tiempos de atención de medicos titulares, y una distribución Generalized para los médicos suplentes.

 Con las funciones de densidad obtenidas generamos los datos simulados y pudimos verificar mediante histogramas que sus valores se ajustan a la forma de los datos originales, lo cual demuestra su validación.

 En conclusión, el trabajo permitió obtener modelos probabilísticos representativos del sistema real.
"""